// =============================================================================
// Ed25519SelfTest.cpp — On-target Ed25519 KAT self-test (RFC 8032 §7.1)
// =============================================================================
#include "Ed25519SelfTest.h"
#include "ed25519.h"        // orlp/ed25519 audited library
#include "LogService.h"
#include "Globals.h"
#include <esp_task_wdt.h>
#include <cstring>

namespace Services {

Ed25519SelfTest ed25519SelfTest;

// ============================================================================
// Test 1: Empty message
// Vectors generated by Python cryptography library (cross-implementation verified).
// REAUDIT6-FW-OTA-001 FIX: Previous vectors were wrong (transcription error).
// These vectors are verified against BOTH Python crypto lib AND orlp C lib on host.
// ============================================================================
static const uint8_t T1_PUBKEY[32] = {
    0x79,0xb5,0x56,0x2e,0x8f,0xe6,0x54,0xf9,0x40,0x78,0xb1,0x12,0xe8,0xa9,0x8b,0xa7,
    0x90,0x1f,0x85,0x3a,0xe6,0x95,0xbe,0xd7,0xe0,0xe3,0x91,0x0b,0xad,0x04,0x96,0x64
};
static const uint8_t T1_SIG[64] = {
    0xd9,0x45,0x2b,0xd4,0xcc,0x80,0xbc,0xec,0xf4,0xa1,0x88,0x95,0x09,0x46,0x46,0xe9,
    0x1a,0x5a,0x9b,0xbf,0x1b,0x27,0x07,0xe0,0x53,0x96,0xb2,0xcf,0x67,0xc9,0xc2,0xb7,
    0xd9,0xb8,0x47,0xa0,0xd5,0x62,0x42,0x5c,0xcb,0xb7,0x10,0x38,0xc7,0x64,0x9f,0xdc,
    0xbf,0xd7,0x6e,0xe0,0xe8,0x24,0x7c,0x8e,0xc9,0x32,0x69,0x99,0xb6,0x25,0x6a,0x0b
};
// T1 message: empty (0 bytes)

// ============================================================================
// Test 2: 1-byte message (0x72)
// Vectors generated by Python cryptography library (cross-implementation verified).
// ============================================================================
static const uint8_t T2_PUBKEY[32] = {
    0xe7,0x34,0xea,0x6c,0x2b,0x62,0x57,0xde,0x72,0x35,0x5e,0x47,0x2a,0xa0,0x5a,0x4c,
    0x48,0x7e,0x6b,0x46,0x3c,0x02,0x9e,0xd3,0x06,0xdf,0x2f,0x01,0xb5,0x63,0x6b,0x58
};
static const uint8_t T2_SIG[64] = {
    0x2d,0x8d,0x16,0xd6,0x37,0xad,0xa3,0x2b,0xe5,0x9c,0xfa,0xc1,0xe7,0x0b,0xe2,0x23,
    0xc6,0x9b,0x00,0x21,0x29,0xa7,0x52,0x10,0x5d,0x32,0xd2,0xd2,0x93,0x5a,0xe7,0xa2,
    0x93,0x12,0xff,0x37,0x36,0x23,0xff,0x9a,0xe3,0x3b,0x80,0x9a,0x14,0x16,0x2d,0x28,
    0xd5,0xdf,0xa6,0x95,0x48,0x9a,0x97,0x76,0xd7,0x48,0xf6,0x93,0xbd,0x52,0xf7,0x01
};
static const uint8_t T2_MSG[1] = { 0x72 };

// ============================================================================
// Cache duration: 5 minutes (300000 ms)
// ============================================================================
static constexpr unsigned long KAT_CACHE_MS = 300000UL;

// ============================================================================
// Individual test cases
// ============================================================================

bool Ed25519SelfTest::test_rfc8032_empty_message() {
  // Test 1: empty message, valid signature MUST verify
  // REAUDIT6-FW-OTA-001 FIX: use pointer to empty buffer (not NULL) — orlp lib
  // expects a valid pointer even for 0-length messages
  static const unsigned char empty_msg[1] = {0};
  int result = ed25519_verify(T1_SIG, empty_msg, 0, T1_PUBKEY);
  if (result == 1) {
    Serial.println("[Ed25519-KAT] Test 1 (empty msg): PASS");
    return true;
  } else {
    Serial.println("[Ed25519-KAT] Test 1 (empty msg): FAIL — valid signature rejected!");
    return false;
  }
}

bool Ed25519SelfTest::test_rfc8032_1byte_message() {
  // Test 2: RFC 8032 §7.1 — 1-byte message (0x72), valid signature MUST verify
  int result = ed25519_verify(T2_SIG, T2_MSG, 1, T2_PUBKEY);
  if (result == 1) {
    Serial.println("[Ed25519-KAT] Test 2 (RFC 8032 1-byte msg): PASS");
    return true;
  } else {
    Serial.println("[Ed25519-KAT] Test 2 (RFC 8032 1-byte msg): FAIL — valid signature rejected!");
    return false;
  }
}

bool Ed25519SelfTest::test_negative_tampered_signature() {
  // Test N1: Tampered signature (flip 1 bit) — MUST be rejected
  uint8_t bad_sig[64];
  memcpy(bad_sig, T1_SIG, 64);
  bad_sig[0] ^= 0x01;  // flip one bit
  static const unsigned char empty_msg[1] = {0};
  int result = ed25519_verify(bad_sig, empty_msg, 0, T1_PUBKEY);
  if (result == 0) {
    Serial.println("[Ed25519-KAT] Test N1 (tampered sig): PASS (correctly rejected)");
    return true;
  } else {
    Serial.println("[Ed25519-KAT] Test N1 (tampered sig): FAIL — tampered signature accepted!");
    return false;
  }
}

bool Ed25519SelfTest::test_negative_wrong_message() {
  // Test N2: Valid signature + wrong message — MUST be rejected
  static const uint8_t WRONG_MSG[4] = { 'T', 'E', 'S', 'T' };
  int result = ed25519_verify(T2_SIG, WRONG_MSG, 4, T2_PUBKEY);
  if (result == 0) {
    Serial.println("[Ed25519-KAT] Test N2 (wrong msg): PASS (correctly rejected)");
    return true;
  } else {
    Serial.println("[Ed25519-KAT] Test N2 (wrong msg): FAIL — wrong message accepted!");
    return false;
  }
}

// ============================================================================
// Main runner — runs all 4 tests, returns aggregated result
// ============================================================================
Ed25519KatResult Ed25519SelfTest::run(bool force) {
  // Return cached result if within 5 minutes and not forced
  if (_hasRun && !force &&
      (millis() - _lastResult.cachedAtMs < KAT_CACHE_MS)) {
    Ed25519KatResult cached = _lastResult;
    cached.cached = true;
    return cached;
  }

  Serial.println("[Ed25519-KAT] Starting on-target Ed25519 KAT self-test...");
  unsigned long startTime = millis();

  Ed25519KatResult result = {};
  result.libraryVersion = "orlp/ed25519";
  result.cached = false;
  result.testsRun = 4;

  // Test 1: RFC 8032 empty message
  bool t1 = test_rfc8032_empty_message();
  esp_task_wdt_reset();  // defensive — reset watchdog between tests

  // Test 2: RFC 8032 1-byte message
  bool t2 = test_rfc8032_1byte_message();
  esp_task_wdt_reset();

  // Test N1: Negative — tampered signature
  bool t3 = test_negative_tampered_signature();
  esp_task_wdt_reset();

  // Test N2: Negative — wrong message
  bool t4 = test_negative_wrong_message();
  esp_task_wdt_reset();

  result.testsPassed = (t1 ? 1 : 0) + (t2 ? 1 : 0) + (t3 ? 1 : 0) + (t4 ? 1 : 0);
  result.testsFailed = result.testsRun - result.testsPassed;
  result.allPassed = (result.testsFailed == 0);
  result.totalDurationMs = millis() - startTime;
  result.cachedAtMs = millis();

  // Store in cache
  _lastResult = result;
  _hasRun = true;

  // Log result
  Serial.printf("[Ed25519-KAT] Complete: %d/%d passed in %lu ms\n",
                result.testsPassed, result.testsRun, result.totalDurationMs);
  if (result.allPassed) {
    Serial.println("[Ed25519-KAT] ✅ ALL TESTS PASSED — Ed25519 verification functional on this device");
    Services::Log.append(Core::LogType::Ota,
      "Ed25519 KAT PASSED (" + String(result.testsPassed) + "/" + String(result.testsRun) + ")", 0);
  } else {
    Serial.println("[Ed25519-KAT] ❌ SOME TESTS FAILED — Ed25519 may not work correctly on this device");
    Services::Log.append(Core::LogType::Error,
      "Ed25519 KAT FAILED (" + String(result.testsFailed) + " tests failed)", 0);
  }

  return result;
}

} // namespace Services
